---
abstract: 'Declarative syntax for Moose'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Declare
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Devel::Declare: 0.005011
  List::MoreUtils: 0
  Moose: 0.89
  MooseX::AttributeHelpers: 0
  MooseX::Method::Signatures: 0.24
  MooseX::Role::Parameterized: 0.12
  MooseX::Types::Moose: 0
  namespace::autoclean: 0.05
  namespace::clean: 0.11
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Declare
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rafl/moosex-declare.git
version: 0.29
