---
abstract: 'Declarative syntax for Moose'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  Test::Exception: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Declare
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0
  Devel::Declare: 0.003000
  Moose: 0
  MooseX::Method::Signatures: 0.06
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
